// Title: DataBar Barcode Image Caching Example
// Description: Demonstrates generating DataBar barcodes with in‑memory caching to reduce redundant image creation in high‑traffic scenarios.
// Category-Description: This example belongs to the Aspose.BarCode barcode generation category, focusing on DataBar symbologies. It showcases the use of BarcodeGenerator, encoding types, and image saving APIs, illustrating typical patterns for developers who need to generate barcode images repeatedly while optimizing performance through caching. Suitable for web services, batch processing, or any application requiring fast repeated barcode rendering.
// Prompt: Implement caching for generated DataBar barcode images to improve high‑traffic web performance.
// Tags: databar, barcode, caching, image generation, aspnet, aspose.barcode, png

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

/// <summary>
/// Provides an example of generating DataBar barcode images with in‑memory caching to improve performance.
/// </summary>
class Program
{
    // Simple in‑memory cache: key = "EncodeType|CodeText", value = PNG bytes
    private static readonly Dictionary<string, byte[]> _cache = new Dictionary<string, byte[]>();

    /// <summary>
    /// Generates a DataBar barcode image or returns a cached image if it already exists.
    /// </summary>
    /// <param name="codeText">The text to encode in the barcode.</param>
    /// <param name="encodeType">The DataBar symbology to use.</param>
    /// <returns>Byte array containing the PNG image.</returns>
    private static byte[] GetBarcodeImage(string codeText, BaseEncodeType encodeType)
    {
        // Build a unique cache key based on symbology and text
        string key = $"{encodeType}|{codeText}";

        // Return cached bytes if present
        if (_cache.TryGetValue(key, out byte[] cachedBytes))
        {
            Console.WriteLine($"Cache hit for {key}");
            return cachedBytes;
        }

        // Cache miss – generate a new barcode image
        Console.WriteLine($"Cache miss for {key}, generating image...");
        using (var generator = new BarcodeGenerator(encodeType, codeText))
        {
            // Use interpolation auto‑size mode for consistent image dimensions
            generator.Parameters.AutoSizeMode = AutoSizeMode.Interpolation;
            generator.Parameters.ImageWidth.Point = 300f;
            generator.Parameters.ImageHeight.Point = 150f;

            // Save the generated image into a memory stream
            using (var ms = new MemoryStream())
            {
                generator.Save(ms, BarCodeImageFormat.Png);
                byte[] imageBytes = ms.ToArray();

                // Store the generated bytes in the cache for future reuse
                _cache[key] = imageBytes;
                return imageBytes;
            }
        }
    }

    /// <summary>
    /// Entry point. Generates sample DataBar barcodes, saves them, and demonstrates cache reuse.
    /// </summary>
    static void Main()
    {
        // Define sample DataBar types with appropriate code texts
        var samples = new List<(BaseEncodeType type, string text)>
        {
            (EncodeTypes.DatabarOmniDirectional, "(01)12345678901231"),
            (EncodeTypes.DatabarLimited, "(01)08888888888888"),
            (EncodeTypes.DatabarStacked, "(01)12345678901231"),
            (EncodeTypes.DatabarExpanded, "(01)12345678901231"),
            (EncodeTypes.DatabarStackedOmniDirectional, "(01)12345678901231")
        };

        // Ensure the output directory exists
        string outputDir = "Barcodes";
        if (!Directory.Exists(outputDir))
        {
            Directory.CreateDirectory(outputDir);
        }

        // Generate each barcode, save to file, and output status
        foreach (var (type, text) in samples)
        {
            byte[] pngBytes = GetBarcodeImage(text, type);
            string fileName = $"{type}_{text.Replace('(', '_').Replace(')', '_').Replace(' ', '_')}.png";
            string filePath = Path.Combine(outputDir, fileName);
            File.WriteAllBytes(filePath, pngBytes);
            Console.WriteLine($"Saved barcode to {filePath}");
        }

        // Demonstrate cache reuse by requesting the first barcode again
        byte[] cachedBytes = GetBarcodeImage(samples[0].text, samples[0].type);
        Console.WriteLine($"Retrieved cached image of size {cachedBytes.Length} bytes.");
    }
}