using System;
using System.Collections.Generic;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing.Imaging;

/// <summary>
/// Provides a simple in‑memory cache for barcode images generated with Aspose.BarCode.
/// </summary>
class BarcodeCache
{
    // Thread‑unsafe dictionary used as a cache; key is a combination of encode type and code text.
    private static readonly Dictionary<string, byte[]> _cache = new Dictionary<string, byte[]>();

    /// <summary>
    /// Retrieves a barcode image as a byte array. If the image has been generated before,
    /// it is returned from the cache; otherwise a new image is generated, cached, and returned.
    /// </summary>
    /// <param name="encodeType">The barcode symbology to use.</param>
    /// <param name="codeText">The text to encode in the barcode.</param>
    /// <returns>Byte array containing the PNG image of the barcode.</returns>
    public static byte[] GetBarcodeImage(BaseEncodeType encodeType, string codeText)
    {
        // Build a unique cache key from the encode type and the text.
        string key = $"{encodeType}_{codeText}";

        // Try to get a cached image.
        if (_cache.TryGetValue(key, out byte[] cachedBytes))
        {
            Console.WriteLine($"Cache hit for key: {key}");
            return cachedBytes;
        }

        // Cache miss – generate a new barcode image.
        Console.WriteLine($"Cache miss for key: {key}. Generating barcode...");
        using (var generator = new BarcodeGenerator(encodeType, codeText))
        {
            // No special parameters needed for DataBar generation in this example.
            using (var ms = new MemoryStream())
            {
                // Save the generated barcode to a memory stream in PNG format.
                generator.Save(ms, BarCodeImageFormat.Png);
                byte[] bytes = ms.ToArray();

                // Store the generated bytes in the cache for future requests.
                _cache[key] = bytes;
                return bytes;
            }
        }
    }
}

/// <summary>
/// Demonstrates barcode generation and caching using <see cref="BarcodeCache"/>.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the application. Generates sample DataBar barcodes,
    /// saves them to files, and shows cache behavior.
    /// </summary>
    static void Main()
    {
        // Sample DataBar symbologies and corresponding code texts.
        var samples = new List<(BaseEncodeType type, string text)>
        {
            (EncodeTypes.DatabarOmniDirectional, "(01)12345678901231"),
            (EncodeTypes.DatabarStacked, "(01)12345678901231"),
            (EncodeTypes.DatabarLimited, "(01)08888888888888")
        };

        int index = 1;
        foreach (var sample in samples)
        {
            // First retrieval (generates and caches).
            byte[] imageBytes = BarcodeCache.GetBarcodeImage(sample.type, sample.text);
            string fileName = $"databar_{index}.png";

            // Write the generated image to disk.
            File.WriteAllBytes(fileName, imageBytes);
            Console.WriteLine($"Saved barcode to {fileName}");

            // Second retrieval (should hit cache).
            byte[] cachedBytes = BarcodeCache.GetBarcodeImage(sample.type, sample.text);
            Console.WriteLine($"Cached image size: {cachedBytes.Length} bytes");
            index++;
        }

        Console.WriteLine("Barcode generation and caching demo completed.");
    }
}