// Title: Generate Code128 barcode and obtain raw PNG byte array
// Description: Demonstrates creating a Code128 barcode with Aspose.BarCode, saving it to a memory stream in PNG format, and extracting the raw byte array for network transmission.
// Category-Description: This example belongs to the Aspose.BarCode image generation category, illustrating how to use BarcodeGenerator and related parameter classes to customize barcode appearance, render the image to a stream, and retrieve binary data. Developers working with barcode creation for web services, APIs, or file storage commonly need to generate barcodes on‑the‑fly and send the resulting bytes over the network. The snippet showcases key classes such as BarcodeGenerator, EncodeTypes, BarCodeImageFormat, and the Parameters property for visual tweaks.
// Prompt: Use BarCodeBuilder to create a barcode and retrieve the raw byte array for network transmission.
// Tags: barcode, code128, generation, png, bytearray, network, aspose.barcode, barcodegenerator

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing;

/// <summary>
/// Demonstrates barcode generation and raw byte extraction using Aspose.BarCode.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point. Generates a Code128 barcode, saves it as PNG to a memory stream,
    /// and obtains the byte array for further processing or transmission.
    /// </summary>
    static void Main()
    {
        // Initialize a barcode generator for Code128 with the desired text
        using (BarcodeGenerator generator = new BarcodeGenerator(EncodeTypes.Code128, "123ABC"))
        {
            // Optional: customize the barcode's foreground and background colors
            generator.Parameters.Barcode.BarColor = Color.Black;
            generator.Parameters.BackColor = Color.White;

            // Create a memory stream to hold the generated PNG image
            using (MemoryStream ms = new MemoryStream())
            {
                // Save the barcode image into the memory stream in PNG format
                generator.Save(ms, BarCodeImageFormat.Png);

                // Convert the stream contents to a raw byte array for transmission
                byte[] barcodeBytes = ms.ToArray();

                // Example usage: display the size of the generated byte array
                Console.WriteLine($"Generated barcode byte array length: {barcodeBytes.Length}");
            }
        }
    }
}