// Title: Generate barcode and obtain raw byte array using Aspose.BarCode
// Description: Demonstrates creating a Code128 barcode with Aspose.BarCode and extracting the PNG image as a byte array suitable for network transmission.
// Category-Description: This example belongs to the Aspose.BarCode generation category, illustrating how to use the BarcodeGenerator (and optionally BarCodeBuilder) classes to produce barcodes, render them to an image format, and retrieve the raw bytes. Typical use cases include embedding barcodes in documents, sending them over network APIs, or storing them in databases. Developers often need to obtain the byte array of the generated image for further processing without writing to disk.
// Prompt: Use BarCodeBuilder to create a barcode and retrieve the raw byte array for network transmission.
// Tags: barcode, code128, generation, raw-bytes, network, aspose.barcode, png

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing;

/// <summary>
/// Example program that generates a Code128 barcode and extracts its PNG image as a raw byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the application. Attempts to locate BarCodeBuilder via reflection; if unavailable,
    /// falls back to using BarcodeGenerator to create the barcode and obtain the image bytes.
    /// </summary>
    static void Main()
    {
        // Attempt to locate BarCodeBuilder type via reflection.
        Type builderType = Type.GetType("Aspose.BarCode.Generation.BarCodeBuilder, Aspose.BarCode");
        if (builderType != null)
        {
            // BarCodeBuilder is present, but this example does not implement its usage.
            Console.WriteLine("BarCodeBuilder type found, but specific usage is not implemented in this example.");
            return;
        }

        // Fallback: use BarcodeGenerator to create a Code128 barcode and retrieve raw PNG bytes.
        using (var generator = new BarcodeGenerator(EncodeTypes.Code128, "123456"))
        {
            using (var memoryStream = new MemoryStream())
            {
                // Save the generated barcode image to the memory stream in PNG format.
                generator.Save(memoryStream, BarCodeImageFormat.Png);

                // Convert the stream contents to a byte array.
                byte[] barcodeBytes = memoryStream.ToArray();

                // Output the length of the generated byte array (for demonstration purposes).
                Console.WriteLine("Generated barcode byte array length: " + barcodeBytes.Length);

                // Example placeholder: transmit barcodeBytes over a network here.
            }
        }
    }
}