// Title: Generate Code128 barcode and obtain raw PNG byte array
// Description: Demonstrates creating a Code128 barcode with Aspose.BarCode, converting it to a PNG image, and extracting the raw byte array for transmission.
// Category-Description: This example belongs to the Aspose.BarCode generation category, illustrating how to use BarcodeGenerator, Bitmap, and ImageFormat to produce barcode images. Typical use cases include creating barcodes for labels, receipts, or embedding in network messages where the image must be sent as a byte stream. Developers often need to retrieve the image bytes for APIs, web services, or storage without writing to disk.
// Prompt: Use BarCodeBuilder to create a barcode and retrieve the raw byte array for network transmission.
// Tags: barcode, code128, generation, png, bytearray, aspose.barcode, aspose.drawing

using System;
using System.IO;
using Aspose.BarCode.Generation;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

/// <summary>
/// Example program that generates a Code128 barcode, saves it to a memory stream as PNG,
/// and retrieves the raw byte array for further processing or network transmission.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Creates the barcode, extracts its byte representation,
    /// and writes the length of the resulting array to the console.
    /// </summary>
    static void Main()
    {
        // Variable to hold the final barcode byte array
        byte[] barcodeBytes;

        // Initialize the barcode generator with Code128 symbology
        using (BarcodeGenerator generator = new BarcodeGenerator(EncodeTypes.Code128))
        {
            // Set the data to be encoded in the barcode
            generator.CodeText = "1234567890";

            // Generate the barcode image as a Bitmap object
            using (Bitmap bitmap = generator.GenerateBarCodeImage())
            {
                // Create a memory stream to hold the image data
                using (MemoryStream ms = new MemoryStream())
                {
                    // Save the bitmap to the memory stream in PNG format
                    bitmap.Save(ms, ImageFormat.Png);

                    // Convert the stream contents to a byte array
                    barcodeBytes = ms.ToArray();
                }
            }
        }

        // Output the size of the generated byte array for verification
        Console.WriteLine($"Generated barcode byte array length: {barcodeBytes.Length}");
    }
}