using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Demonstrates generating a GS1‑128 barcode using Aspose.BarCode,
/// saving the image bytes to a file, and optionally writing the PNG image.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the application.
    /// Generates a GS1‑128 barcode, captures its PNG bytes,
    /// and writes the bytes to disk for demonstration purposes.
    /// </summary>
    static void Main()
    {
        // Define the barcode content.
        // GS1 Code 128 requires AI parentheses, e.g., (01) for GTIN.
        string codeText = "(01)12345678901231";

        // Variable to hold the generated barcode image bytes.
        byte[] barcodeBytes;

        // Use a memory stream to capture the PNG image generated by Aspose.BarCode.
        using (var memoryStream = new MemoryStream())
        {
            // Create a barcode generator for GS1‑128 with the specified text.
            using (var generator = new BarcodeGenerator(EncodeTypes.GS1Code128, codeText))
            {
                // Optional: display the checksum digit in the human‑readable text.
                generator.Parameters.Barcode.ChecksumAlwaysShow = true;

                // Save the barcode image to the memory stream in PNG format.
                generator.Save(memoryStream, BarCodeImageFormat.Png);
            }

            // Convert the memory stream contents to a byte array.
            barcodeBytes = memoryStream.ToArray();
        }

        // ----------------------------------------------------------------------
        // In a real application you would store 'barcodeBytes' in a database column.
        // For this example (no database available) we write the bytes to a file.
        // ----------------------------------------------------------------------
        string binaryPath = "barcode_image.bin";

        // Write the raw PNG bytes to a binary file.
        File.WriteAllBytes(binaryPath, barcodeBytes);
        Console.WriteLine($"Barcode image bytes written to {binaryPath}");

        // Additionally, save the same PNG bytes with a .png extension for visual verification.
        string pngPath = "gs1code128.png";

        // Write the PNG image to disk.
        File.WriteAllBytes(pngPath, barcodeBytes);
        Console.WriteLine($"Barcode PNG saved to {pngPath}");
    }
}