// Title: Generate Han Xin barcode as PNG byte array
// Description: Demonstrates creating a Han Xin barcode image and returning it as a PNG byte array, suitable for embedding in email attachments.
// Category-Description: This example belongs to the Aspose.BarCode generation category, showcasing how to use the BarcodeGenerator class with EncodeTypes.HanXin. It covers setting error correction levels, handling invalid code text, and exporting the barcode to a memory stream in PNG format. Developers working with barcode creation for documents, emails, or web services often need to produce image data directly without writing to disk.
// Prompt: Create method that returns Han Xin barcode as byte array for inclusion in email attachments.
// Tags: hanxin, barcode, generation, png, byte-array, aspose.barcode, email-attachment

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Example program that generates a Han Xin barcode and returns it as a PNG byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Generates a barcode, displays its size, and optionally saves it to a temporary file.
    /// </summary>
    static void Main()
    {
        // Sample text to encode in the Han Xin barcode
        string sampleText = "Sample Han Xin Barcode";

        // Generate the barcode image as a byte array
        byte[] barcodeBytes = CreateHanXinBarcode(sampleText);

        // Show the length of the generated byte array
        Console.WriteLine($"Generated barcode byte array length: {barcodeBytes.Length}");

        // Optional: write the byte array to a temporary PNG file for visual verification
        string outputPath = Path.Combine(Path.GetTempPath(), "hanxin.png");
        File.WriteAllBytes(outputPath, barcodeBytes);
        Console.WriteLine($"Barcode saved to: {outputPath}");
    }

    /// <summary>
    /// Creates a Han Xin barcode image and returns it as a PNG byte array.
    /// </summary>
    /// <param name="codeText">The text to encode in the barcode.</param>
    /// <returns>Byte array containing the PNG image of the barcode.</returns>
    static byte[] CreateHanXinBarcode(string codeText)
    {
        if (string.IsNullOrEmpty(codeText))
            throw new ArgumentException("codeText cannot be null or empty.", nameof(codeText));

        // Initialize the barcode generator for Han Xin symbology with the provided text
        using (var generator = new BarcodeGenerator(EncodeTypes.HanXin, codeText))
        {
            // Set Reed‑Solomon error correction level to L2 (example configuration)
            generator.Parameters.Barcode.HanXin.ErrorLevel = HanXinErrorLevel.L2;

            // Allow the generator to continue even if the code text is slightly incorrect
            generator.Parameters.Barcode.ThrowExceptionWhenCodeTextIncorrect = false;

            // Save the barcode image to a memory stream in PNG format
            using (var ms = new MemoryStream())
            {
                generator.Save(ms, BarCodeImageFormat.Png);
                // Return the image data as a byte array
                return ms.ToArray();
            }
        }
    }
}