// Title: Generate Han Xin barcode as byte array for email attachments
// Description: Demonstrates creating a Han Xin (Chinese 2D) barcode image in PNG format and returning it as a byte array, suitable for embedding in email messages.
// Category-Description: This example belongs to the Aspose.BarCode generation category, illustrating how to use the BarcodeGenerator class with EncodeTypes.HanXin to produce barcode images. Typical use cases include creating barcodes for documents, emails, or reports where the image must be transmitted as binary data. Developers often need to configure symbology-specific parameters and retrieve the image as a byte array for further processing or attachment.
// Prompt: Create method that returns Han Xin barcode as byte array for inclusion in email attachments.
// Tags: hanxin, barcode generation, png, byte array, aspose.barcode, barcodegenerator

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Provides an example of generating a Han Xin barcode and returning it as a byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Generates a barcode for sample text and writes the byte array length to the console.
    /// </summary>
    static void Main()
    {
        // Sample text to encode in the Han Xin barcode.
        string sampleText = "HanXin Sample 123";

        // Generate the barcode and obtain the PNG image as a byte array.
        byte[] barcodeBytes = GetHanXinBarcodeBytes(sampleText);

        // Output the size of the generated byte array.
        Console.WriteLine($"Generated Han Xin barcode byte array length: {barcodeBytes.Length}");
    }

    /// <summary>
    /// Generates a Han Xin barcode image in PNG format and returns it as a byte array.
    /// </summary>
    /// <param name="codeText">The text to encode in the Han Xin barcode.</param>
    /// <returns>Byte array containing the PNG image of the generated barcode.</returns>
    public static byte[] GetHanXinBarcodeBytes(string codeText)
    {
        // Validate input to ensure a non‑empty string is provided.
        if (string.IsNullOrEmpty(codeText))
            throw new ArgumentException("Code text must be a non-empty string.", nameof(codeText));

        // Initialize the barcode generator for Han Xin symbology with the supplied text.
        using (var generator = new BarcodeGenerator(EncodeTypes.HanXin, codeText))
        {
            // Set a moderate error correction level (L2) for the barcode.
            generator.Parameters.Barcode.HanXin.ErrorLevel = HanXinErrorLevel.L2;

            // Use a memory stream to capture the generated PNG image.
            using (var ms = new MemoryStream())
            {
                // Save the barcode image to the memory stream in PNG format.
                generator.Save(ms, BarCodeImageFormat.Png);

                // Return the image data as a byte array.
                return ms.ToArray();
            }
        }
    }
}