// Title: Generate QR Code and embed into PDF report
// Description: Demonstrates creating a QR Code barcode with Aspose.BarCode, customizing its appearance, and inserting it into a PDF document using Aspose.Pdf along with descriptive text.
// Category-Description: This example belongs to the Aspose.BarCode barcode generation and Aspose.Pdf document creation category. It showcases the use of BarcodeGenerator (for QR Code creation), EncodeTypes, QRErrorLevel, BarCodeImageFormat, and the Aspose.Pdf Document, Page, TextFragment, and Image classes. Typical scenarios include generating barcodes for reports, invoices, tickets, or any printable material where a visual barcode must be combined with textual information. Developers often need to customize barcode appearance and embed the resulting image into PDF files for distribution or archival.
// Prompt: Generate QR Code barcode and embed it into a PDF report alongside descriptive text.
// Tags: qr code, barcode generation, pdf creation, aspose.barcode, aspose.pdf, image embedding, c#

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Pdf;
using Aspose.Pdf.Text;

/// <summary>
/// Example program that creates a QR Code barcode and embeds it into a PDF report.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the application. Generates a QR Code, adds descriptive text,
    /// embeds the barcode image into a PDF, and saves the document to a temporary location.
    /// </summary>
    static void Main()
    {
        // Define the output PDF file path in the system's temporary folder.
        string outputPdf = Path.Combine(Path.GetTempPath(), "QrReport.pdf");

        // Create a memory stream to hold the generated barcode image.
        using (var barcodeStream = new MemoryStream())
        {
            // Generate a QR Code barcode with custom parameters.
            using (var generator = new BarcodeGenerator(EncodeTypes.QR, "https://example.com"))
            {
                // Set high error correction level for better readability.
                generator.Parameters.Barcode.QR.ErrorLevel = QRErrorLevel.LevelH;
                // Define the size of a single QR module in pixels.
                generator.Parameters.Barcode.XDimension.Pixels = 4f;
                // Set barcode foreground and background colors.
                generator.Parameters.Barcode.BarColor = Aspose.Drawing.Color.Black;
                generator.Parameters.BackColor = Aspose.Drawing.Color.White;
                // Save the barcode as a PNG image into the memory stream.
                generator.Save(barcodeStream, BarCodeImageFormat.Png);
            }

            // Reset stream position to the beginning before reading.
            barcodeStream.Position = 0;

            // Create a new PDF document.
            using (var pdfDoc = new Document())
            {
                // Add a page to the document.
                var page = pdfDoc.Pages.Add();

                // Add descriptive text above the barcode.
                var text = new TextFragment("QR Code generated by Aspose.BarCode and embedded in this PDF.");
                page.Paragraphs.Add(text);

                // Create an image object from the barcode stream and configure its layout.
                var pdfImage = new Image
                {
                    ImageStream = barcodeStream,
                    FixWidth = 150,
                    FixHeight = 150,
                    HorizontalAlignment = HorizontalAlignment.Center,
                    VerticalAlignment = VerticalAlignment.Center,
                    Margin = new MarginInfo { Top = 10 }
                };
                // Add the barcode image to the page.
                page.Paragraphs.Add(pdfImage);

                // Save the PDF document to the specified file.
                pdfDoc.Save(outputPdf);
            }
        }

        // Inform the user where the PDF report was saved.
        Console.WriteLine($"PDF report generated at: {outputPdf}");
    }
}