// Title: Generate QR Code and embed into PDF report
// Description: Demonstrates creating a QR Code barcode, saving it as an image, and inserting it into a PDF document with descriptive text.
// Category-Description: This example belongs to the Aspose.BarCode PDF integration category, illustrating how to use BarcodeGenerator (Aspose.BarCode.Generation) to produce QR Code images and embed them into Aspose.Pdf documents. Typical use cases include generating barcode‑enhanced reports, invoices, or tickets where a QR Code links to online resources. Developers often need to combine barcode generation with PDF creation, adjusting image size, alignment, and adding explanatory text.
// Prompt: Generate QR Code barcode and embed it into a PDF report alongside descriptive text.
// Tags: qr code, barcode generation, pdf creation, aspose.barcode, aspose.pdf, image embedding

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Pdf;
using Aspose.Pdf.Text;

/// <summary>
/// Example program that generates a QR Code barcode and embeds it into a PDF report with descriptive text.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the application. Generates a QR Code, creates a PDF, adds explanatory text and the QR image, then saves the file.
    /// </summary>
    static void Main()
    {
        // Define the output PDF file name
        string outputPdfPath = "QrReport.pdf";

        // Initialize the QR Code generator with the target URL
        using (var generator = new BarcodeGenerator(EncodeTypes.QR, "https://example.com"))
        {
            // Configure the QR Code to use the highest error correction level
            generator.Parameters.Barcode.QR.ErrorLevel = QRErrorLevel.LevelH;

            // Render the barcode to a memory stream in PNG format
            using (var barcodeStream = new MemoryStream())
            {
                generator.Save(barcodeStream, BarCodeImageFormat.Png);
                barcodeStream.Position = 0; // Reset stream position for subsequent reading

                // Create a new PDF document
                using (var pdfDoc = new Document())
                {
                    // Add a single page to the document
                    var page = pdfDoc.Pages.Add();

                    // Insert descriptive text at the top of the page
                    var textFragment = new TextFragment("QR Code generated by Aspose.BarCode");
                    textFragment.TextState.FontSize = 12;
                    textFragment.TextState.Font = FontRepository.FindFont("Arial");
                    page.Paragraphs.Add(textFragment);

                    // Add a blank line for spacing
                    page.Paragraphs.Add(new TextFragment("\n"));

                    // Embed the QR Code image into the PDF
                    var pdfImage = new Aspose.Pdf.Image
                    {
                        ImageStream = barcodeStream,
                        FixWidth = 200,
                        FixHeight = 200,
                        HorizontalAlignment = HorizontalAlignment.Center
                    };
                    page.Paragraphs.Add(pdfImage);

                    // Save the assembled PDF to disk
                    pdfDoc.Save(outputPdfPath);
                }

                // barcodeStream is disposed here after the PDF has been saved
            }
        }

        // Output the full path of the generated PDF for user reference
        Console.WriteLine($"PDF report generated: {Path.GetFullPath(outputPdfPath)}");
    }
}