using System;
using System.IO;
using System.Threading.Tasks;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Demonstrates asynchronous barcode generation using Aspose.BarCode.
/// </summary>
class Program
{
    /// <summary>
    /// Generates a barcode image asynchronously and returns the image data as a byte array.
    /// </summary>
    /// <param name="encodeType">The type of barcode to generate (e.g., Code128).</param>
    /// <param name="codeText">The text to encode in the barcode.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains the PNG image bytes.</returns>
    static async Task<byte[]> GenerateBarcodeAsync(BaseEncodeType encodeType, string codeText)
    {
        // Offload the generation to a background thread to avoid blocking the calling thread.
        return await Task.Run(() =>
        {
            // Initialize the barcode generator with the specified encoding type and text.
            using (var generator = new BarcodeGenerator(encodeType, codeText))
            {
                // Create a memory stream to hold the generated PNG image.
                using (var ms = new MemoryStream())
                {
                    // Save the barcode image into the memory stream in PNG format.
                    generator.Save(ms, BarCodeImageFormat.Png);
                    // Return the image data as a byte array.
                    return ms.ToArray();
                }
            }
        });
    }

    /// <summary>
    /// Application entry point. Generates a sample barcode, displays its size, and saves it to a file.
    /// </summary>
    /// <param name="args">Command-line arguments (not used).</param>
    static async Task Main(string[] args)
    {
        // Generate a Code128 barcode with the sample text "123ABC".
        byte[] barcodeBytes = await GenerateBarcodeAsync(EncodeTypes.Code128, "123ABC");

        // Output the length of the generated byte array to the console.
        Console.WriteLine($"Generated barcode byte array length: {barcodeBytes.Length}");

        // Define the output file path for the barcode image.
        const string outputPath = "barcode.png";

        // Write the PNG image bytes to the file asynchronously.
        await File.WriteAllBytesAsync(outputPath, barcodeBytes);
        Console.WriteLine($"Barcode image saved to: {outputPath}");
    }
}