// Title: Generate DataMatrix barcode as PNG byte array
// Description: Demonstrates creating a DataMatrix barcode and returning it as a PNG byte array for embedding in PDF documents.
// Category-Description: This example belongs to the Aspose.BarCode generation category, illustrating how to use the BarcodeGenerator class to produce DataMatrix symbology. Typical use cases include embedding barcodes in PDFs, reports, or other documents where a byte array representation is required. Developers often need to customize barcode parameters and retrieve the image in memory without writing to disk.
// Prompt: Implement method that returns DataMatrix barcode as byte array for embedding in PDF documents.
// Tags: datamatrix, barcode, generation, png, bytearray, aspose.barcode, pdf

using System;
using System.IO;
using Aspose.BarCode.Generation;
using Aspose.BarCode;

/// <summary>
/// Provides functionality to generate a DataMatrix barcode and obtain its PNG representation as a byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Generates a DataMatrix barcode image and returns it as a PNG byte array.
    /// </summary>
    /// <param name="codeText">The text to encode in the barcode.</param>
    /// <returns>Byte array containing the PNG image of the generated barcode.</returns>
    static byte[] GenerateDataMatrixBarcode(string codeText)
    {
        // Initialize the barcode generator for DataMatrix with the supplied text.
        using (var generator = new BarcodeGenerator(EncodeTypes.DataMatrix, codeText))
        {
            // Optional: customize barcode parameters here (e.g., version, ECC level).
            // generator.Parameters.Barcode.DataMatrix.DataMatrixVersion = DataMatrixVersion.ECC200_20x20;

            // Save the generated barcode to a memory stream in PNG format.
            using (var memoryStream = new MemoryStream())
            {
                generator.Save(memoryStream, BarCodeImageFormat.Png);
                // Return the stream contents as a byte array.
                return memoryStream.ToArray();
            }
        }
    }

    /// <summary>
    /// Entry point of the example. Generates a sample DataMatrix barcode and displays the byte array length.
    /// </summary>
    static void Main()
    {
        // Sample text to encode in the DataMatrix barcode.
        string sampleText = "Sample DataMatrix";

        // Generate the barcode as a PNG byte array.
        byte[] barcodeBytes = GenerateDataMatrixBarcode(sampleText);

        // Output the size of the generated byte array for verification.
        Console.WriteLine($"Generated DataMatrix barcode byte array length: {barcodeBytes.Length}");

        // Optional: write the byte array to a file for visual verification.
        // File.WriteAllBytes("datamatrix.png", barcodeBytes);
    }
}