// Title: GS1 Composite Barcode Image Caching Example
// Description: Demonstrates how to cache generated GS1 Composite barcode images in memory to avoid redundant generation for identical requests.
// Category-Description: This example belongs to the Aspose.BarCode image generation category, showcasing the use of BarcodeGenerator, EncodeTypes, and GS1CompositeBar parameters. Developers often need to generate barcodes repeatedly in web or desktop applications; caching the resulting image bytes improves performance and reduces CPU load. The pattern illustrated here is common for high‑throughput scenarios where the same barcode data is requested multiple times.
// Prompt: Implement caching of generated GS1 Composite barcode images to improve performance for repeated requests.
// Tags: gs1 composite, barcode caching, image generation, aspose.barcode, c#

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Provides an in‑memory cache for barcode image byte arrays keyed by barcode content and configuration.
/// </summary>
class BarcodeCache
{
    // Internal dictionary storing generated image data keyed by a composite string.
    private readonly Dictionary<string, byte[]> _cache = new Dictionary<string, byte[]>();

    /// <summary>
    /// Retrieves a cached barcode image or generates a new one if not present.
    /// </summary>
    /// <param name="codeText">The raw data to encode in the barcode.</param>
    /// <param name="linearComponent">The linear component type (e.g., GS1‑Code128).</param>
    /// <param name="twoDComponent">The 2‑D component type (e.g., CC_A or CC_B).</param>
    /// <returns>Byte array containing the PNG image of the generated barcode.</returns>
    public byte[] GetOrCreate(string codeText, BaseEncodeType linearComponent, TwoDComponentType twoDComponent)
    {
        // Build a unique cache key from the input parameters.
        string key = $"{codeText}|{linearComponent}|{twoDComponent}";

        // Return cached data if it exists.
        if (_cache.TryGetValue(key, out var data))
        {
            Console.WriteLine($"Cache hit for key: {key}");
            return data;
        }

        // Cache miss – generate a new barcode image.
        Console.WriteLine($"Generating barcode for key: {key}");
        using (var generator = new BarcodeGenerator(EncodeTypes.GS1CompositeBar, codeText))
        {
            // Configure GS1 Composite barcode specifics.
            generator.Parameters.Barcode.GS1CompositeBar.LinearComponentType = linearComponent;
            generator.Parameters.Barcode.GS1CompositeBar.TwoDComponentType = twoDComponent;
            generator.Parameters.Barcode.GS1CompositeBar.AllowOnlyGS1Encoding = false;
            generator.Parameters.Barcode.XDimension.Pixels = 2f;

            // Save the generated image to a memory stream.
            using (var ms = new MemoryStream())
            {
                generator.Save(ms, BarCodeImageFormat.Png);
                data = ms.ToArray();

                // Store the generated bytes in the cache for future requests.
                _cache[key] = data;
                return data;
            }
        }
    }
}

/// <summary>
/// Demonstrates usage of <see cref="BarcodeCache"/> to generate and cache GS1 Composite barcodes.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Generates three barcode images, reusing the cached result for identical parameters.
    /// </summary>
    static void Main()
    {
        // Instantiate the cache manager.
        var cache = new BarcodeCache();

        // Define barcode data and component types.
        string code = "(01)98898765432106|(10)0123";
        BaseEncodeType linear = EncodeTypes.GS1Code128;
        TwoDComponentType twoD_A = TwoDComponentType.CC_A;
        TwoDComponentType twoD_B = TwoDComponentType.CC_B;

        // First request (generates and caches the image).
        byte[] img1 = cache.GetOrCreate(code, linear, twoD_A);
        File.WriteAllBytes("barcode1.png", img1);

        // Second request with the same parameters (retrieved from cache).
        byte[] img2 = cache.GetOrCreate(code, linear, twoD_A);
        File.WriteAllBytes("barcode2.png", img2);

        // Third request with a different 2‑D component (generates a new image).
        byte[] img3 = cache.GetOrCreate(code, linear, twoD_B);
        File.WriteAllBytes("barcode3.png", img3);
    }
}