// Title: Generate DataMatrix barcode as PNG byte array
// Description: Demonstrates creating a DataMatrix barcode image in PNG format and returning it as a byte array, which can be embedded directly into PDF documents.
// Category-Description: This example belongs to the Aspose.BarCode generation category, illustrating how to use the BarcodeGenerator class with EncodeTypes.DataMatrix to produce barcode images. Typical use cases include embedding barcodes in PDFs, reports, or other documents where a byte array representation is required. Developers often need to configure encoding modes, set image formats, and retrieve the image data without writing to disk.
// Prompt: Implement method that returns DataMatrix barcode as byte array for embedding in PDF documents.
// Tags: datamatrix, barcode, generation, png, byte-array, aspose.barcode, pdf-embedding

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing.Imaging;

/// <summary>
/// Example program that generates a DataMatrix barcode image and returns it as a byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point. Generates a sample DataMatrix barcode, displays its byte length, and saves it to a file for verification.
    /// </summary>
    static void Main()
    {
        // Text to encode in the DataMatrix barcode
        string sampleText = "Sample123";

        // Generate the barcode image as a PNG byte array
        byte[] barcodeBytes = GenerateDataMatrixBarcode(sampleText);

        // Show the size of the generated byte array
        Console.WriteLine($"Generated DataMatrix barcode byte array length: {barcodeBytes.Length}");

        // Optional: write the image to disk so the result can be inspected manually
        string outputPath = "datamatrix.png";
        File.WriteAllBytes(outputPath, barcodeBytes);
        Console.WriteLine($"Barcode image saved to: {Path.GetFullPath(outputPath)}");
    }

    /// <summary>
    /// Generates a DataMatrix barcode image in PNG format and returns it as a byte array.
    /// </summary>
    /// <param name="codeText">The text to encode in the barcode.</param>
    /// <returns>Byte array containing the PNG image of the barcode.</returns>
    static byte[] GenerateDataMatrixBarcode(string codeText)
    {
        if (string.IsNullOrEmpty(codeText))
            throw new ArgumentException("Code text must not be null or empty.", nameof(codeText));

        // Use a memory stream to avoid writing to the file system
        using (var memoryStream = new MemoryStream())
        {
            // Initialize the barcode generator for DataMatrix with the provided text
            using (var generator = new BarcodeGenerator(EncodeTypes.DataMatrix, codeText))
            {
                // Enable Unicode support via ECI encoding (UTF-8)
                generator.Parameters.Barcode.DataMatrix.EncodeMode = DataMatrixEncodeMode.ECI;
                generator.Parameters.Barcode.DataMatrix.ECIEncoding = ECIEncodings.UTF8;

                // Save the generated barcode to the memory stream in PNG format
                generator.Save(memoryStream, BarCodeImageFormat.Png);
            }

            // Return the raw PNG bytes
            return memoryStream.ToArray();
        }
    }
}