// Title: Generate MaxiCode barcode and return as byte array
// Description: Demonstrates creating a MaxiCode (Mode 4) barcode, saving it to a MemoryStream, and obtaining the PNG byte array.
// Category-Description: This example belongs to the Aspose.BarCode generation category, illustrating how to use BarcodeGenerator with EncodeTypes.MaxiCode, configure MaxiCode parameters, and export the image in PNG format. Developers working with shipping labels, package tracking, or other logistics solutions often need to programmatically produce MaxiCode barcodes and handle the resulting byte data for storage or transmission.
// Prompt: Save generated MaxiCode barcode to a MemoryStream and return the byte array to the caller.
// Tags: maxicode, generate, png, barcodegenerator, encodetypes, barcodelimageformat

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Demonstrates generating a MaxiCode barcode and retrieving its PNG byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point. Creates a MaxiCode barcode, writes it to a MemoryStream, and outputs the byte array length.
    /// </summary>
    static void Main()
    {
        // Sample code text for MaxiCode (Mode 4 allows arbitrary text)
        string codeText = "Hello MaxiCode";

        // Initialize the barcode generator for MaxiCode with the provided text
        using (BarcodeGenerator generator = new BarcodeGenerator(EncodeTypes.MaxiCode, codeText))
        {
            // Configure MaxiCode specific settings: use Mode 4 and set pixel size
            generator.Parameters.Barcode.MaxiCode.Mode = MaxiCodeMode.Mode4;
            generator.Parameters.Barcode.XDimension.Pixels = 15f;

            // Create a memory stream to hold the generated PNG image
            using (MemoryStream ms = new MemoryStream())
            {
                // Save the barcode image into the stream in PNG format
                generator.Save(ms, BarCodeImageFormat.Png);

                // Convert the stream contents to a byte array for further use
                byte[] barcodeBytes = ms.ToArray();

                // Display the size of the generated byte array (for demonstration)
                Console.WriteLine($"Generated MaxiCode barcode byte array length: {barcodeBytes.Length}");
                // Optionally, display the image as a Base64 string (commented out to avoid large output)
                // Console.WriteLine(Convert.ToBase64String(barcodeBytes));
            }
        }
    }
}