// Title: Generate MaxiCode barcode and return as byte array
// Description: Demonstrates creating a MaxiCode barcode, saving it to a MemoryStream in PNG format, and obtaining the resulting byte array.
// Category-Description: This example belongs to the Aspose.BarCode generation category, illustrating how to use the BarcodeGenerator class with EncodeTypes.MaxiCode to produce barcodes, configure parameters such as XDimension and MaxiCode mode, and output the image to a MemoryStream. Developers working with barcode creation often need to generate images in memory for further processing, storage, or transmission, and this snippet shows the typical steps and API usage.
// Prompt: Save generated MaxiCode barcode to a MemoryStream and return the byte array to the caller.
// Tags: maxicode, barcode generation, png, memorystream, aspose.barcode, aspose.barcode.generation

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing.Imaging;

/// <summary>
/// Example program that generates a MaxiCode barcode, writes it to a MemoryStream,
/// and returns the image as a byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Generates the barcode and outputs the byte array length.
    /// </summary>
    static void Main()
    {
        // Sample codetext containing Unicode characters
        string codeText = "Åspóse.Barcóde©";

        // Create a memory stream to hold the generated barcode image
        using (MemoryStream memoryStream = new MemoryStream())
        {
            // Initialize the barcode generator for MaxiCode with the provided text
            using (BarcodeGenerator generator = new BarcodeGenerator(EncodeTypes.MaxiCode, codeText))
            {
                // Set the size of a single module (pixel) in the barcode
                generator.Parameters.Barcode.XDimension.Pixels = 15f;

                // Choose the MaxiCode mode (Mode4 allows arbitrary text)
                generator.Parameters.Barcode.MaxiCode.Mode = MaxiCodeMode.Mode4;

                // Save the generated barcode image to the memory stream in PNG format
                generator.Save(memoryStream, BarCodeImageFormat.Png);
            }

            // Convert the memory stream contents to a byte array
            byte[] barcodeBytes = memoryStream.ToArray();

            // Output information about the generated byte array
            Console.WriteLine($"Generated MaxiCode barcode byte array length: {barcodeBytes.Length}");

            // Optional: write the image to a file for visual verification
            File.WriteAllBytes("maxicode.png", barcodeBytes);
        }
    }
}