using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.BarCode.ComplexBarcode;

/// <summary>
/// Demonstrates generation of a MaxiCode barcode using Aspose.BarCode library.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the application. Generates a MaxiCode barcode, displays its byte array length,
    /// and optionally writes the image to a file.
    /// </summary>
    static void Main()
    {
        // Generate the MaxiCode barcode and obtain its byte array.
        byte[] barcodeBytes = GenerateMaxiCode();

        // Output the size of the generated byte array.
        Console.WriteLine($"Generated MaxiCode barcode byte array length: {barcodeBytes.Length}");

        // Optional: write the image to a file for visual verification.
        File.WriteAllBytes("maxicode.png", barcodeBytes);
    }

    /// <summary>
    /// Creates a MaxiCode barcode in Mode 2 with a standard second message and returns the image as a byte array.
    /// </summary>
    /// <returns>Byte array containing the PNG representation of the generated barcode.</returns>
    static byte[] GenerateMaxiCode()
    {
        // Prepare the MaxiCode codetext for Mode 2 with a standard second message.
        var maxiCodeCodetext = new MaxiCodeCodetextMode2
        {
            PostalCode = "524032140",
            CountryCode = 56,
            ServiceCategory = 999
        };

        // Create the second message to be embedded in the barcode.
        var secondMessage = new MaxiCodeStandardSecondMessage
        {
            Message = "Test message"
        };
        maxiCodeCodetext.SecondMessage = secondMessage;

        // Generate the barcode image into a memory stream and return the byte array.
        using (var memoryStream = new MemoryStream())
        {
            // Initialize the barcode generator with the prepared codetext.
            using (var generator = new ComplexBarcodeGenerator(maxiCodeCodetext))
            {
                // Save the generated barcode as PNG into the memory stream.
                generator.Save(memoryStream, BarCodeImageFormat.Png);
            }

            // Convert the memory stream contents to a byte array.
            return memoryStream.ToArray();
        }
    }
}