using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

class Program
{
    // Simulates a REST endpoint that receives postal barcode data and returns the image as a byte array.
    static byte[] GeneratePostalBarcode(string postalData)
    {
        if (string.IsNullOrWhiteSpace(postalData))
            throw new ArgumentException("Postal data must not be empty.", nameof(postalData));

        // Create a memory stream to hold the PNG image.
        using (var memoryStream = new MemoryStream())
        {
            // Initialize the barcode generator for Postnet symbology with the provided data.
            using (var generator = new BarcodeGenerator(EncodeTypes.Postnet, postalData))
            {
                // Optional: customize appearance (e.g., bar color).
                generator.Parameters.Barcode.BarColor = Aspose.Drawing.Color.Black;

                // Save the generated barcode image to the memory stream in PNG format.
                generator.Save(memoryStream, BarCodeImageFormat.Png);
            }

            // Return the image bytes.
            return memoryStream.ToArray();
        }
    }

    static void Main()
    {
        // Sample postal barcode data (e.g., ZIP code for Postnet).
        string sampleData = "12345";

        // Generate the barcode image bytes.
        byte[] barcodeBytes = GeneratePostalBarcode(sampleData);

        // Output the size of the generated byte array to verify execution.
        Console.WriteLine($"Generated barcode image byte array length: {barcodeBytes.Length}");
    }
}