// Title: Generate MaxiCode Postal Barcode and Return as Byte Array
// Description: Demonstrates generating a MaxiCode postal barcode from input data and retrieving the image as a PNG byte array.
// Category-Description: This example belongs to the Aspose.BarCode generation category, showcasing how to use the BarcodeGenerator class with EncodeTypes.MaxiCode to create postal barcodes. Typical use cases include producing shipping label barcodes, integrating barcode images into web services, and converting them to byte arrays for API responses. Developers often need to configure dimensions, select symbology modes, and output images in common formats such as PNG.
// Prompt: Build a REST API endpoint that receives postal barcode data and returns the image as a byte array.
// Tags: maxicode, postal barcode, barcode generation, png, byte array, aspose.barcode, c#

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Provides functionality to generate a MaxiCode postal barcode and obtain the image as a byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Simulates receiving postal data, generates the barcode, and outputs the byte array length.
    /// </summary>
    static void Main()
    {
        // Simulated request payload containing postal barcode data
        string postalData = "SamplePostalData";

        // Generate the barcode image and obtain it as a byte array
        byte[] barcodeBytes = GeneratePostalBarcode(postalData);

        // Output the size of the generated byte array (for demonstration purposes)
        Console.WriteLine($"Generated barcode byte array length: {barcodeBytes.Length}");
    }

    /// <summary>
    /// Generates a MaxiCode barcode image from the supplied data and returns the image as a PNG byte array.
    /// </summary>
    /// <param name="data">The postal data to encode in the barcode.</param>
    /// <returns>Byte array containing the PNG representation of the generated barcode.</returns>
    static byte[] GeneratePostalBarcode(string data)
    {
        // Validate input data
        if (string.IsNullOrEmpty(data))
            throw new ArgumentException("Data must be non-empty.", nameof(data));

        // Create a barcode generator for the MaxiCode symbology using the provided data
        using (var generator = new BarcodeGenerator(EncodeTypes.MaxiCode, data))
        {
            // Configure barcode appearance: set X-dimension (module size) in pixels
            generator.Parameters.Barcode.XDimension.Pixels = 4f;

            // Optional: set a specific MaxiCode mode if required
            // generator.Parameters.Barcode.MaxiCode.Mode = MaxiCodeMode.Mode4;

            // Write the barcode image to a memory stream in PNG format
            using (var ms = new MemoryStream())
            {
                generator.Save(ms, BarCodeImageFormat.Png);
                // Return the image data as a byte array
                return ms.ToArray();
            }
        }
    }
}