using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

namespace BarcodeExample
{
    class Program
    {
        static void Main()
        {
            // Create a barcode generator for RM4SCC with sample code text
            using (BarcodeGenerator generator = new BarcodeGenerator(EncodeTypes.RM4SCC, "1234567890"))
            {
                // Set custom XDimension (smallest bar width) in points
                generator.Parameters.Barcode.XDimension.Point = 2f;

                // Generate the barcode image as a Bitmap
                using (Bitmap bitmap = generator.GenerateBarCodeImage())
                {
                    // Save the bitmap to a memory stream in PNG format
                    using (MemoryStream ms = new MemoryStream())
                    {
                        bitmap.Save(ms, ImageFormat.Png);
                        byte[] imageBytes = ms.ToArray();

                        // Example usage: output the size of the generated byte array
                        Console.WriteLine($"Generated barcode image byte array length: {imageBytes.Length}");
                    }
                }
            }
        }
    }
}