// Title: Generate RM4SCC Barcode and Export as PNG Byte Array
// Description: Demonstrates creating a RM4SCC barcode, customizing its X‑dimension, and saving the image to a memory stream as a PNG byte array.
// Category-Description: This example belongs to the Aspose.BarCode generation category, showcasing how to use the BarcodeGenerator class with EncodeTypes to produce barcodes. Typical use cases include creating barcodes for product labeling, inventory tracking, and document automation. Developers often need to adjust visual parameters (e.g., XDimension) and export the result in various image formats using BarCodeImageFormat.
// Prompt: Create a barcode generator instance for RM4SCC, set custom XDimension, and export image to a byte array.
// Tags: rm4scc, barcode generation, xdimension, png, byte array, aspose.barcode, c#

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Example program that generates an RM4SCC barcode, customizes its X‑dimension,
/// and outputs the PNG image as a byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Creates the barcode, saves it to a memory stream,
    /// converts it to a byte array, and writes the array length to the console.
    /// </summary>
    static void Main()
    {
        // Initialize the barcode generator for RM4SCC symbology with the desired data.
        using (var generator = new BarcodeGenerator(EncodeTypes.RM4SCC, "123456"))
        {
            // Set a custom X‑dimension (module width) in pixels.
            generator.Parameters.Barcode.XDimension.Pixels = 3f;

            // Create a memory stream to hold the generated PNG image.
            using (var ms = new MemoryStream())
            {
                // Save the barcode image to the memory stream in PNG format.
                generator.Save(ms, BarCodeImageFormat.Png);

                // Convert the stream contents to a byte array.
                byte[] imageBytes = ms.ToArray();

                // Output the length of the generated byte array.
                Console.WriteLine($"Generated barcode byte array length: {imageBytes.Length}");
            }
        }
    }
}