// Title: Generate RM4SCC barcode with custom XDimension and export to byte array
// Description: Demonstrates creating an Aspose.BarCode generator for the RM4SCC symbology, customizing the XDimension, and exporting the resulting PNG image to a byte array.
// Category-Description: This example belongs to the barcode generation category of Aspose.BarCode, illustrating how to configure barcode parameters such as XDimension and retrieve the image as a byte array. It showcases the use of BarcodeGenerator, EncodeTypes, and image handling classes, which are common tasks for developers needing programmatic barcode creation for documents, labels, or web services.
// Prompt: Create a barcode generator instance for RM4SCC, set custom XDimension, and export image to a byte array.
// Tags: rm4scc, barcode generation, xdimension, byte array, png, aspnet, aspose.barcode, image export

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

namespace BarcodeExample
{
    /// <summary>
    /// Provides an example of generating an RM4SCC barcode, customizing its XDimension,
    /// and exporting the resulting image to a byte array.
    /// </summary>
    class Program
    {
        /// <summary>
        /// Entry point of the example. Creates a barcode, sets a custom module width,
        /// and writes the image size to the console.
        /// </summary>
        static void Main()
        {
            // Initialize a barcode generator for the RM4SCC symbology
            using (var generator = new BarcodeGenerator(EncodeTypes.RM4SCC))
            {
                // Define the data to encode in the barcode
                generator.CodeText = "A1234567890";

                // Set a custom XDimension (module width) measured in points
                generator.Parameters.Barcode.XDimension.Point = 2f;

                // Generate the barcode image as a Bitmap object
                using (Bitmap bitmap = generator.GenerateBarCodeImage())
                {
                    // Prepare a memory stream to hold the PNG-encoded image
                    using (var memoryStream = new MemoryStream())
                    {
                        // Save the bitmap to the stream in PNG format
                        bitmap.Save(memoryStream, ImageFormat.Png);

                        // Retrieve the image bytes from the stream
                        byte[] barcodeBytes = memoryStream.ToArray();

                        // Output the length of the generated byte array for verification
                        Console.WriteLine($"Generated barcode byte array length: {barcodeBytes.Length}");
                    }
                }
            }
        }
    }
}