using System;
using System.IO;
using System.Text;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.BarCode.BarCodeRecognition;

/// <summary>
/// Demonstrates generating a QR barcode with Unicode text and reading it back,
/// verifying that encoding detection works correctly.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the application.
    /// Generates a QR code from a Unicode string, reads it back, and validates the decoded text.
    /// </summary>
    static void Main()
    {
        // Sample text containing Unicode characters (Russian phrase "Hello, world!").
        const string originalText = "Привет, мир!";

        // Byte array that will hold the generated barcode image.
        byte[] barcodeBytes;

        // Generate the QR barcode and store it in a memory stream.
        using (var ms = new MemoryStream())
        {
            // Create a barcode generator for QR codes.
            using (var generator = new BarcodeGenerator(EncodeTypes.QR))
            {
                // Encode the text using UTF-16 Big Endian (includes BOM) to preserve Unicode characters.
                generator.SetCodeText(originalText, Encoding.BigEndianUnicode);

                // Save the generated barcode as a PNG image into the memory stream.
                generator.Save(ms, BarCodeImageFormat.Png);
            }

            // Convert the memory stream contents to a byte array for later processing.
            barcodeBytes = ms.ToArray();
        }

        // Read and decode the barcode from the previously generated byte array.
        using (var imageStream = new MemoryStream(barcodeBytes))
        {
            // Ensure the stream is positioned at the beginning before reading.
            imageStream.Position = 0;

            // Initialize a barcode reader that supports all barcode types.
            using (var reader = new BarCodeReader(imageStream, DecodeType.AllSupportedTypes))
            {
                // Explicitly enable encoding detection (true by default) for clarity.
                reader.BarcodeSettings.DetectEncoding = true;

                // Iterate over all detected barcodes in the image.
                foreach (var result in reader.ReadBarCodes())
                {
                    // Output the type of barcode that was detected.
                    Console.WriteLine($"Detected Type: {result.CodeTypeName}");

                    // Output the decoded text from the barcode.
                    Console.WriteLine($"Decoded Text : {result.CodeText}");

                    // Verify that the decoded text matches the original Unicode string.
                    if (result.CodeText == originalText)
                    {
                        Console.WriteLine("Encoding detection succeeded: decoded text matches original.");
                    }
                    else
                    {
                        Console.WriteLine("Encoding detection failed: decoded text does not match original.");
                    }
                }
            }
        }
    }
}