// Title: Generate Mailmark Barcode to MemoryStream and Return PNG Bytes
// Description: Demonstrates creating a Mailmark barcode with Aspose.BarCode, saving it as a PNG image into a MemoryStream, and retrieving the raw byte array for use in a web API.
// Category-Description: This example belongs to the Aspose.BarCode complex barcode generation category. It showcases the use of the ComplexBarcodeGenerator class to produce Mailmark (4‑state) barcodes, a common requirement for postal services and logistics applications. Developers often need to generate barcode images on‑the‑fly and return them as byte streams for web services, mobile apps, or document workflows.
// Prompt: Generate a Mailmark barcode into a MemoryStream and return image bytes to a web API.
// Tags: mailmark, barcode generation, png, memorystream, complexbarcodegenerator, aspose.barcode, web api

using System;
using System.IO;
using Aspose.BarCode.ComplexBarcode;
using Aspose.BarCode.Generation;

namespace MailmarkBarcodeExample
{
    /// <summary>
    /// Provides an entry point that creates a Mailmark barcode, saves it to a MemoryStream,
    /// and outputs the resulting PNG byte array length. Intended for integration with a web API.
    /// </summary>
    class Program
    {
        /// <summary>
        /// Main method that builds the Mailmark codetext, generates the barcode image,
        /// and extracts the PNG bytes from a MemoryStream.
        /// </summary>
        static void Main()
        {
            // Initialize Mailmark codetext with required fields.
            var mailmark = new MailmarkCodetext
            {
                Format = 4,                     // 4‑state Mailmark format
                VersionID = 1,
                Class = "0",
                SupplychainID = 384224,
                ItemID = 16563762,
                DestinationPostCodePlusDPS = "EF61AH8T " // trailing space is required
            };

            // Create a MemoryStream to hold the generated PNG image.
            using (var memoryStream = new MemoryStream())
            {
                // Generate the barcode using ComplexBarcodeGenerator and save as PNG.
                using (var generator = new ComplexBarcodeGenerator(mailmark))
                {
                    generator.Save(memoryStream, BarCodeImageFormat.Png);
                }

                // Retrieve the PNG image bytes from the MemoryStream.
                byte[] imageBytes = memoryStream.ToArray();

                // Demonstrate that the image was generated by writing the byte array length.
                Console.WriteLine($"Mailmark barcode image generated. Byte array length: {imageBytes.Length}");
            }
        }
    }
}