using System;
using Aspose.BarCode.Generation;
using Aspose.Drawing;

class Program
{
    // Retrieves the actual pixel dimensions of the barcode image generated by the provided generator.
    static (int Width, int Height) GetBarcodePixelDimensions(BarcodeGenerator generator)
    {
        // Generate the barcode image according to current settings.
        using (Bitmap bitmap = generator.GenerateBarCodeImage())
        {
            // Width and Height properties are expressed in pixels.
            return (bitmap.Width, bitmap.Height);
        }
    }

    static void Main()
    {
        // Create a barcode generator for Code128.
        using (var generator = new BarcodeGenerator(EncodeTypes.Code128))
        {
            // Set the text to encode.
            generator.CodeText = "1234567890";

            // Set resolution (dpi). This influences how unit values are converted to pixels.
            generator.Parameters.Resolution = 300f; // 300 DPI

            // Define desired image size using point units.
            // 1 point = 1/72 inch. At 300 DPI, 200 points ≈ 833 pixels.
            generator.Parameters.ImageWidth.Point = 200f;
            generator.Parameters.ImageHeight.Point = 100f;

            // Optionally, set XDimension and BarHeight using point units.
            generator.Parameters.Barcode.XDimension.Point = 2f; // 2 points
            generator.Parameters.Barcode.BarHeight.Point = 40f; // 40 points

            // Retrieve actual pixel dimensions.
            var (width, height) = GetBarcodePixelDimensions(generator);

            // Output the results.
            Console.WriteLine($"Barcode pixel dimensions: Width = {width} px, Height = {height} px");

            // Save the barcode image for visual verification (optional).
            generator.Save("barcode.png");
        }
    }
}