// Title: Generate Swiss QR Code PNG as Byte Array
// Description: Demonstrates creating a Swiss QR Code barcode and returning its PNG representation as a byte array.
// Category-Description: This example belongs to the Aspose.BarCode barcode generation category, focusing on complex barcode types such as Swiss QR Codes. It showcases the use of ComplexBarcodeGenerator, SwissQRCodetext, and related parameter settings to produce high‑resolution PNG images. Developers working with payment QR codes, invoicing, or Swiss QR Bill standards commonly use these APIs to embed payment information in a scannable format.
// Prompt: Create a .NET method that accepts parameters and returns a byte array of the Swiss QR Code PNG.
// Tags: swissqr, barcode, generation, png, aspose.barcode

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.BarCode.ComplexBarcode;

/// <summary>
/// Example program that generates a Swiss QR Code and returns the PNG image as a byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Generates a Swiss QR Code PNG and writes its size and location to the console.
    /// </summary>
    static void Main()
    {
        // Sample data for Swiss QR Code
        string account = "CH4431999123000889012";
        decimal amount = 1000.25m;
        string creditorName = "Muster & Söhne";

        // Generate the QR code PNG bytes
        byte[] pngBytes = GenerateSwissQrCode(account, amount, creditorName);

        // Output the length of the generated byte array
        Console.WriteLine($"Generated Swiss QR Code PNG byte array length: {pngBytes.Length}");

        // Optionally write the PNG to a temporary file for verification
        string outputPath = Path.Combine(Path.GetTempPath(), "SwissQRBill.png");
        File.WriteAllBytes(outputPath, pngBytes);
        Console.WriteLine($"PNG saved to: {outputPath}");
    }

    /// <summary>
    /// Generates a Swiss QR Code barcode using the provided account, amount, and creditor name,
    /// and returns the resulting PNG image as a byte array.
    /// </summary>
    /// <param name="account">Swiss QR account number (IBAN).</param>
    /// <param name="amount">Payment amount; must be greater than zero.</param>
    /// <param name="creditorName">Name of the creditor.</param>
    /// <returns>Byte array containing the PNG representation of the Swiss QR Code.</returns>
    static byte[] GenerateSwissQrCode(string account, decimal amount, string creditorName)
    {
        // Validate input parameters
        if (string.IsNullOrWhiteSpace(account))
            throw new ArgumentException("Account must be provided.", nameof(account));
        if (amount <= 0)
            throw new ArgumentOutOfRangeException(nameof(amount), "Amount must be greater than zero.");
        if (string.IsNullOrWhiteSpace(creditorName))
            throw new ArgumentException("Creditor name must be provided.", nameof(creditorName));

        // Create Swiss QR Code data structure
        SwissQRCodetext swissQr = new SwissQRCodetext();
        swissQr.Bill.Version = SwissQRBill.QrBillStandardVersion.V2_0;
        swissQr.Bill.Account = account;
        swissQr.Bill.Amount = amount;
        swissQr.Bill.Currency = "CHF";
        swissQr.Bill.Reference = ""; // optional reference
        swissQr.Bill.Creditor = new Address
        {
            Name = creditorName,
            CountryCode = "CH"
        };

        // Initialize the complex barcode generator with the Swiss QR data
        using (ComplexBarcodeGenerator generator = new ComplexBarcodeGenerator(swissQr))
        {
            // Configure barcode appearance and encoding
            generator.Parameters.Barcode.XDimension.Pixels = 4;
            generator.Parameters.Barcode.QR.EncodeMode = QREncodeMode.ECI;
            generator.Parameters.Barcode.QR.ECIEncoding = ECIEncodings.UTF8;

            // Render the barcode to a memory stream in PNG format
            using (MemoryStream ms = new MemoryStream())
            {
                generator.Save(ms, BarCodeImageFormat.Png);
                return ms.ToArray(); // Return the PNG bytes
            }
        }
    }
}