using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.ComplexBarcode;
using Aspose.BarCode.Generation;

namespace BarcodeDemo
{
    /// <summary>
    /// Demonstrates generation of a Swiss QR Code barcode and saving it as a PNG file.
    /// </summary>
    class Program
    {
        /// <summary>
        /// Entry point of the application. Generates a Swiss QR Code PNG byte array,
        /// displays its length, and optionally writes it to a file.
        /// </summary>
        static void Main()
        {
            // Sample data for Swiss QR Code
            string account = "CH9300762011623852957";
            decimal amount = 199.95m;
            string creditorName = "John Doe";

            // Generate PNG bytes using the helper method
            byte[] pngBytes = GenerateSwissQrCode(account, amount, creditorName);

            // Output the size of the generated byte array for verification
            Console.WriteLine($"Generated Swiss QR Code PNG byte array length: {pngBytes.Length}");

            // Save the PNG to disk for manual inspection (optional)
            string outputPath = "SwissQR.png";
            using (var fileStream = new FileStream(outputPath, FileMode.Create, FileAccess.Write))
            {
                fileStream.Write(pngBytes, 0, pngBytes.Length);
            }

            Console.WriteLine($"Saved PNG to {outputPath}");
        }

        // Generates a Swiss QR Code PNG and returns it as a byte array.
        public static byte[] GenerateSwissQrCode(
            string account,
            decimal amount,
            string creditorName,
            string creditorCountryCode = "CH",
            SwissQRBill.QrBillStandardVersion version = SwissQRBill.QrBillStandardVersion.V2_0)
        {
            // Validate required parameters
            if (string.IsNullOrWhiteSpace(account))
                throw new ArgumentException("Account is required.", nameof(account));
            if (string.IsNullOrWhiteSpace(creditorName))
                throw new ArgumentException("Creditor name is required.", nameof(creditorName));

            // Populate Swiss QR codetext with mandatory fields
            var swissQr = new SwissQRCodetext();
            swissQr.Bill.Account = account;
            swissQr.Bill.Amount = amount;
            swissQr.Bill.Creditor.Name = creditorName;
            swissQr.Bill.Creditor.CountryCode = creditorCountryCode;
            swissQr.Bill.Version = version;

            // Generate barcode image into a memory stream and return the bytes
            using (var generator = new ComplexBarcodeGenerator(swissQr))
            {
                using (var ms = new MemoryStream())
                {
                    generator.Save(ms, BarCodeImageFormat.Png);
                    return ms.ToArray();
                }
            }
        }
    }
}