using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

/// <summary>
/// Demonstrates barcode generation using Aspose.BarCode in a console application.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the application. Generates a Code128 barcode, saves it to a file,
    /// and outputs its Base64 representation to the console.
    /// </summary>
    static void Main()
    {
        // NOTE: Full ASP.NET integration cannot be demonstrated in this console app.
        // The core barcode generation logic is shown below. In an ASP.NET controller
        // you would write the generated bytes directly to Response.OutputStream.

        // Create a barcode generator for Code128 with the specified data.
        using (var generator = new BarcodeGenerator(EncodeTypes.Code128, "1234567890"))
        {
            // Optional visual settings: set barcode color and background color.
            generator.Parameters.Barcode.BarColor = Color.Black;
            generator.Parameters.BackColor = Color.White;

            // Use a memory stream to hold the generated image.
            using (var ms = new MemoryStream())
            {
                // Save the barcode image to the memory stream in PNG format.
                generator.Save(ms, BarCodeImageFormat.Png);
                byte[] barcodeBytes = ms.ToArray(); // Convert stream to byte array.

                // ASP.NET example (commented out for console):
                // HttpResponse response = HttpContext.Current.Response;
                // response.ContentType = "image/png";
                // response.AddHeader("Content-Disposition", "attachment; filename=barcode.png");
                // response.OutputStream.Write(barcodeBytes, 0, barcodeBytes.Length);
                // response.End();

                // Console demonstration: write the image to a file.
                File.WriteAllBytes("barcode.png", barcodeBytes);
                Console.WriteLine("Barcode saved to barcode.png");

                // Output the Base64 string of the barcode image.
                Console.WriteLine(Convert.ToBase64String(barcodeBytes));
            }
        }
    }
}