// Title: Compare memory usage of ExportToXml overloads in Aspose.BarCode
// Description: Demonstrates measuring the memory impact of exporting a barcode configuration to XML using a file path versus a memory stream.
// Category-Description: This example belongs to the Aspose.BarCode export operations category, showcasing how to use BarcodeGenerator and its ExportToXml methods. It highlights typical use cases such as persisting barcode settings to XML files or streams, and helps developers understand performance characteristics of different overloads. Ideal for developers optimizing memory usage in barcode generation workflows.
// Prompt: Compare memory usage of ExportToXml(Stream) versus ExportToXml(string) for identical configurations.
// Tags: barcode, export, xml, memory, aspose.barcode, generator, stream, file

using System;
using System.IO;
using System.Diagnostics;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing;

/// <summary>
/// Demonstrates memory usage comparison between ExportToXml(string) and ExportToXml(Stream) overloads.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point. Creates a QR barcode generator, exports its configuration to XML using both overloads,
    /// and reports the memory increase for each method.
    /// </summary>
    static void Main()
    {
        // Prepare a temporary folder to store the XML file generated by ExportToXml(string)
        string tempFolder = Path.Combine(Path.GetTempPath(), "ExportXmlComparison");
        Directory.CreateDirectory(tempFolder);
        string xmlFilePath = Path.Combine(tempFolder, "generator.xml");

        // Initialize a barcode generator with a QR code and sample text
        using (var generator = new BarcodeGenerator(EncodeTypes.QR, "SampleCodeText"))
        {
            // Configure basic visual properties
            generator.Parameters.Barcode.XDimension.Pixels = 2f;
            generator.Parameters.Barcode.BarColor = Color.Black;

            // ------------------------------
            // Measure memory usage for ExportToXml(string)
            // ------------------------------
            GC.Collect();
            GC.WaitForPendingFinalizers();
            long beforeString = GC.GetTotalMemory(true);
            generator.ExportToXml(xmlFilePath); // Export configuration to a file
            long afterString = GC.GetTotalMemory(true);
            long diffString = afterString - beforeString;

            // ------------------------------
            // Measure memory usage for ExportToXml(Stream)
            // ------------------------------
            GC.Collect();
            GC.WaitForPendingFinalizers();
            long beforeStream = GC.GetTotalMemory(true);
            using (var ms = new MemoryStream())
            {
                generator.ExportToXml(ms); // Export configuration to a memory stream
            }
            long afterStream = GC.GetTotalMemory(true);
            long diffStream = afterStream - beforeStream;

            // Output the memory differences for each overload
            Console.WriteLine($"Memory increase after ExportToXml(string): {diffString} bytes");
            Console.WriteLine($"Memory increase after ExportToXml(Stream): {diffStream} bytes");
        }

        // Clean up the temporary XML file and folder
        try
        {
            if (File.Exists(xmlFilePath))
                File.Delete(xmlFilePath);
            if (Directory.Exists(tempFolder))
                Directory.Delete(tempFolder, true);
        }
        catch
        {
            // Ignore any errors during cleanup
        }
    }
}