// Title: Generate Barcode PNG as Byte Array
// Description: Demonstrates how to generate a barcode image in PNG format and return it as a byte array using Aspose.BarCode.
// Category-Description: This example belongs to the Aspose.BarCode generation category, showcasing the use of BarcodeGenerator and BarCodeImageFormat to create barcode images. Typical scenarios include creating barcodes for labels, receipts, or inventory systems where the image needs to be stored or transmitted as binary data. Developers often need a reusable method that accepts encoding parameters and returns the image bytes for further processing.
// Prompt: Create a reusable method that accepts primary data parameters and returns a PNG byte array of generated barcode.
// Tags: barcode, code128, png, byte array, aspose.barcode, generation, image format

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.Drawing;
using Aspose.Drawing.Imaging;

/// <summary>
/// Provides an entry point for the barcode generation example.
/// </summary>
class Program
{
    /// <summary>
    /// Demonstrates the usage of <see cref="GenerateBarcode"/> by creating a Code128 barcode,
    /// outputting its byte length, and saving the PNG image to disk.
    /// </summary>
    static void Main()
    {
        // Define barcode symbology and data to encode
        BaseEncodeType encodeType = EncodeTypes.Code128;
        string codeText = "12345678";

        // Generate the barcode PNG as a byte array
        byte[] pngBytes = GenerateBarcode(encodeType, codeText);

        // Display the size of the generated byte array
        Console.WriteLine($"Generated PNG byte array length: {pngBytes.Length}");

        // Write the PNG bytes to a file for visual verification
        string outputPath = Path.Combine(Directory.GetCurrentDirectory(), "sample_barcode.png");
        File.WriteAllBytes(outputPath, pngBytes);
        Console.WriteLine($"Barcode image saved to: {outputPath}");
    }

    /// <summary>
    /// Generates a barcode image in PNG format and returns it as a byte array.
    /// </summary>
    /// <param name="encodeType">The barcode symbology (e.g., EncodeTypes.Code128).</param>
    /// <param name="codeText">The text to encode in the barcode.</param>
    /// <returns>PNG image bytes representing the generated barcode.</returns>
    static byte[] GenerateBarcode(BaseEncodeType encodeType, string codeText)
    {
        // Validate input parameters
        if (encodeType == null)
            throw new ArgumentNullException(nameof(encodeType));
        if (codeText == null)
            throw new ArgumentNullException(nameof(codeText));

        // Create a BarcodeGenerator with the specified type and data
        using (var generator = new BarcodeGenerator(encodeType, codeText))
        {
            // Optional: adjust module size for better readability
            generator.Parameters.Barcode.XDimension.Pixels = 3f;

            // Save the generated barcode to a memory stream in PNG format
            using (var ms = new MemoryStream())
            {
                generator.Save(ms, BarCodeImageFormat.Png);
                // Return the stream contents as a byte array
                return ms.ToArray();
            }
        }
    }
}