// Title: Generate barcode PNG as byte array
// Description: Demonstrates creating a barcode image in PNG format and returning it as a byte array for further processing or storage.
// Category-Description: This example belongs to the Aspose.BarCode generation category, illustrating how to use the BarcodeGenerator class with AutoSizeMode and Save method to produce PNG images. Developers commonly need to generate barcodes dynamically for reports, labels, or web APIs, and this snippet shows the typical workflow of configuring parameters, encoding data, and retrieving the image as a byte array.
// Prompt: Create a reusable method that accepts primary data parameters and returns a PNG byte array of generated barcode.
// Tags: barcode, symbology, generation, png, byte-array, aspose.barcode, encode-types

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;

/// <summary>
/// Demonstrates barcode generation and returning the image as a PNG byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Generates a barcode image and returns it as a PNG byte array.
    /// </summary>
    /// <param name="codeText">The text to encode.</param>
    /// <param name="encodeType">The barcode symbology (e.g., EncodeTypes.Code128).</param>
    /// <returns>Byte array containing the PNG image.</returns>
    static byte[] GenerateBarcode(string codeText, BaseEncodeType encodeType)
    {
        // Validate input parameters.
        if (string.IsNullOrEmpty(codeText))
            throw new ArgumentException("codeText cannot be null or empty.", nameof(codeText));
        if (encodeType == null)
            throw new ArgumentNullException(nameof(encodeType));

        // Initialize the generator with the specified symbology and data.
        using (var generator = new BarcodeGenerator(encodeType, codeText))
        {
            // Use interpolation mode so the image size adapts to the content.
            generator.Parameters.AutoSizeMode = AutoSizeMode.Interpolation;

            // Save the generated barcode to a memory stream in PNG format.
            using (var ms = new MemoryStream())
            {
                generator.Save(ms, BarCodeImageFormat.Png);
                // Return the stream contents as a byte array.
                return ms.ToArray();
            }
        }
    }

    /// <summary>
    /// Entry point that generates a sample Code128 barcode and writes the PNG to disk.
    /// </summary>
    static void Main()
    {
        // Example: generate a Code128 barcode.
        byte[] pngBytes = GenerateBarcode("1234567890", EncodeTypes.Code128);

        // Output the size of the generated byte array for verification.
        Console.WriteLine($"Generated PNG byte array length: {pngBytes.Length}");

        // Write the PNG to a file for visual verification (optional).
        File.WriteAllBytes("sample.png", pngBytes);
    }
}