// Title: Generate HIBC LIC barcode and return PNG byte array
// Description: Demonstrates creating a HIBC LIC barcode with Aspose.BarCode, saving it as a PNG image into a MemoryStream, and obtaining the byte array for API responses.
// Category-Description: This example belongs to the Aspose.BarCode barcode generation category, focusing on complex barcode types such as HIBC LIC. It showcases the use of ComplexBarcodeGenerator, HIBCLICSecondaryAndAdditionalDataCodetext, and related data classes to encode secondary and additional data. Developers commonly need to generate HIBC barcodes for healthcare product labeling and return the image data via web APIs.
// Prompt: Save the generated HIBC LIC barcode to a MemoryStream and return its byte array for an API response.
// Tags: hibc, lic, barcode generation, png, memorystream, aspose.barcode, complexbarcodegenerator

using System;
using System.IO;
using Aspose.BarCode.Generation;
using Aspose.BarCode.ComplexBarcode;
using Aspose.BarCode;

/// <summary>
/// Example program that generates a HIBC LIC barcode and returns its PNG byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Generates the barcode, saves it to a MemoryStream, and outputs the byte array length.
    /// </summary>
    static void Main()
    {
        // Prepare HIBC LIC secondary and additional data codetext
        var hibcCodetext = new HIBCLICSecondaryAndAdditionalDataCodetext
        {
            // Set the barcode symbology (Code128 LIC in this example)
            BarcodeType = EncodeTypes.HIBCCode128LIC,
            // Link character is mandatory; '+' is the default
            LinkCharacter = '+',
            // Populate secondary data (example fields)
            Data = new SecondaryAndAdditionalData
            {
                LotNumber = "LOT123",
                SerialNumber = "SERIAL123",
                Quantity = 10,
                ExpiryDate = DateTime.Today.AddMonths(6),
                ExpiryDateFormat = HIBCLICDateFormat.MMDDYY,
                DateOfManufacture = DateTime.Today.AddMonths(-1)
            }
        };

        // Generate the barcode and save it to a MemoryStream
        byte[] barcodeBytes;
        using (var generator = new ComplexBarcodeGenerator(hibcCodetext))
        {
            using (var ms = new MemoryStream())
            {
                // Save as PNG image into the stream
                generator.Save(ms, BarCodeImageFormat.Png);
                // Retrieve the byte array for API response
                barcodeBytes = ms.ToArray();
            }
        }

        // Example output: display the size of the generated byte array
        Console.WriteLine($"Generated HIBC LIC barcode byte array length: {barcodeBytes.Length}");
        // The 'barcodeBytes' variable now contains the PNG image data ready for an API response.
    }
}