// Title: Generate HIBC LIC barcode and return as byte array
// Description: This example creates a HIBC QR LIC barcode, renders it to PNG, stores it in a MemoryStream, and extracts the byte array for use in API responses.
// Category-Description: Demonstrates Aspose.BarCode complex barcode generation using the HIBCLICPrimaryDataCodetext class. Typical scenarios include healthcare product labeling, inventory tracking, and regulatory compliance where HIBC‑LIC symbology is required. Developers often need to generate the barcode image in memory and return the raw bytes from a web API, leveraging ComplexBarcodeGenerator and related parameter settings.
// Prompt: Save the generated HIBC LIC barcode to a MemoryStream and return its byte array for an API response.
// Tags: barcode, hibc, lic, png, memorystream, bytearray, aspnet, aspose.barcode, barcode generation

using System;
using System.IO;
using Aspose.BarCode;
using Aspose.BarCode.Generation;
using Aspose.BarCode.ComplexBarcode;

/// <summary>
/// Example program that generates a HIBC QR LIC barcode,
/// saves it to a <see cref="MemoryStream"/>, and returns the image as a byte array.
/// </summary>
class Program
{
    /// <summary>
    /// Entry point of the example. Creates barcode data, generates the image,
    /// and outputs information about the resulting byte array.
    /// </summary>
    static void Main()
    {
        // Initialize primary data for the HIBC LIC barcode
        HIBCLICPrimaryDataCodetext codetext = new HIBCLICPrimaryDataCodetext();
        codetext.BarcodeType = EncodeTypes.HIBCQRLIC;
        codetext.Data = new PrimaryData();
        codetext.Data.ProductOrCatalogNumber = "12345";
        codetext.Data.LabelerIdentificationCode = "A999";
        codetext.Data.UnitOfMeasureID = 1;

        // Generate the barcode image and store it in a byte array
        byte[] barcodeBytes;
        using (var generator = new ComplexBarcodeGenerator(codetext))
        {
            // Adjust image resolution (X dimension) for better clarity
            generator.Parameters.Barcode.XDimension.Pixels = 10f;

            // Render the barcode to a PNG format inside a MemoryStream
            using (var ms = new MemoryStream())
            {
                generator.Save(ms, BarCodeImageFormat.Png);
                barcodeBytes = ms.ToArray(); // Extract the raw bytes
            }
        }

        // Display basic information about the generated byte array
        Console.WriteLine($"Generated HIBC LIC barcode byte array length: {barcodeBytes.Length}");
        // Show the first few bytes as a hexadecimal string for verification
        Console.WriteLine("First 8 bytes: " + BitConverter.ToString(barcodeBytes, 0, Math.Min(8, barcodeBytes.Length)));
    }
}